name: DevSecOps Pipeline

on:
    workflow_dispatch:

jobs:

    Gitleaks:
        name: Git Secrets Scan
        uses: ./.github/workflows/gitleaks.yml
        

    SonarQube:
        needs: Gitleaks
        name: Secuirty_Checks 
        uses: ./.github/workflows/sonarqube.yml

    Linting:
        needs: SonarQube
        name: Check_Code_linting
        uses: ./.github/workflows/linting.yml
    

    
    