name: DevSecOps Pipeline

on:
    workflow_dispatch:

jobs:

    Gitleaks:
        name: Git Secrets Scan
        uses: ./.github/workflows/gitleaks.yml
        

    Linting:
        needs: Gitleaks
        name: Check_Code_linting
        uses: ./.github/workflows/linting.yml
    

    Docker_Build_Push:
        needs: Gitleaks
        name: Docker_Build_Push
        uses: ./.github/workflows/docker_Build_Push.yml
    